server:
  port: 8080  #配置端口号
  tomcat:
    uri-encoding: UTF-8 #uri编码

#############################################
######配置数据源相关 使用HikariCP 数据源
#############################################
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fangwx?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 30000 #超时时长
      minimum-idle: 5    #最小连接数
      maximum-pool-size: 15  #最大连接数
      auto-commit: true   #自动提交
      idle-timeout: 600000 # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DatebookHikariCP #连接池名字
      max-lifetime: 28740000  # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1

#############################################
######mybatis配置
#############################################
mybatis:
  type-aliases-package: com.cz.pojo
  mapper-locations: classpath:mapper/*.xml
#分页插件配置
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql

###########################################
######分布式文件系统fastdfs
############################################
fdfs:
  connect-timeout: 601
  so-timeout: 1501
  thumb-image:
    width: 80
    height: 80
  tracker-list:            #TrackerList参数,支持多个
      - 120.78.95.157:22122
logging:
  level:
    com:
      cz:
        mapper: debug


############################################
####log
############################################